on:
  push:
    branches:
      - master
      - main

jobs:
  call-tmpl-build-release:
    uses: fh-inway/d365.psmodule-alm/.github/workflows/tmpl-build-release.yml@main
    with:
      module: 'd365bap.tools'
    secrets:
      apikey: ${{ secrets.ApiKey }}