on:
  push:
    branches:
      - master
      - main

jobs:
  call-tmpl-build-release:
    uses: ./.github/workflows/tmpl-build-release.yml
    with:
      skippublish: $False
      skipghrelease: $False
    secrets:
      apikey: ${{ secrets.ApiKey }}